export const tweets = [
  {
    id: 1,
    user: "Leanne Graham",
    username: "@Bret",
    avatar: "https://i.pravatar.cc/150?u=Bret",
    content: "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
    comments: 12,
    retweets: 23,
    likes: 101,
    saves: 5,
    stats: 1200,
    shares: 18,
    image: "https://picsum.photos/seed/1/600/400",
  },
  {
    id: 2,
    user: "Ervin Howell",
    username: "@Antonette",
    avatar: "https://i.pravatar.cc/150?u=Antonette",
    content: "qui est esse",
    comments: 4,
    retweets: 11,
    likes: 89,
    saves: 2,
    stats: 850,
    shares: 9,
  },
  {
    id: 3,
    user: "Clementine Bauch",
    username: "@Samantha",
    avatar: "https://i.pravatar.cc/150?u=Samantha",
    content: "ea molestias quasi exercitationem repellat qui ipsa sit aut",
    comments: 2,
    retweets: 5,
    likes: 42,
    saves: 1,
    stats: 500,
    shares: 5,
    image: "https://picsum.photos/seed/2/600/400",
  },
  {
    id: 4,
    user: "Patricia Lebsack",
    username: "@Karianne",
    avatar: "https://i.pravatar.cc/150?u=Karianne",
    content: "eum et est occaecati",
    comments: 8,
    retweets: 17,
    likes: 99,
    saves: 4,
    stats: 1100,
    shares: 15,
  },
  {
    id: 5,
    user: "Chelsey Dietrich",
    username: "@Kamren",
    avatar: "https://i.pravatar.cc/150?u=Kamren",
    content: "nesciunt quas odio",
    comments: 1,
    retweets: 2,
    likes: 15,
    saves: 0,
    stats: 250,
    shares: 2,
    image: "https://picsum.photos/seed/3/600/400",
  },
  {
    id: 6,
    user: "Mrs. Dennis Schulist",
    username: "@Leopoldo_Corkery",
    avatar: "https://i.pravatar.cc/150?u=Leopoldo_Corkery",
    content: "dolorem eum magni eos aperiam quia",
    comments: 3,
    retweets: 8,
    likes: 21,
    saves: 1,
    stats: 300,
    shares: 4,
  },
  {
    id: 7,
    user: "Kurtis Weissnat",
    username: "@Elwyn.Skiles",
    avatar: "https://i.pravatar.cc/150?u=Elwyn.Skiles",
    content: "magnam facilis autem",
    comments: 5,
    retweets: 10,
    likes: 55,
    saves: 3,
    stats: 650,
    shares: 8,
    image: "https://picsum.photos/seed/4/600/400",
  },
  {
    id: 8,
    user: "Nicholas Runolfsdottir V",
    username: "@Maxime_Nienow",
    avatar: "https://i.pravatar.cc/150?u=Maxime_Nienow",
    content: "dolorem dolore est ipsam",
    comments: 7,
    retweets: 15,
    likes: 78,
    saves: 2,
    stats: 900,
    shares: 12,
  },
  {
    id: 9,
    user: "Glenna Reichert",
    username: "@Delphine",
    avatar: "https://i.pravatar.cc/150?u=Delphine",
    content: "consequatur autem doloribus natus laudantium",
    comments: 11,
    retweets: 22,
    likes: 110,
    saves: 6,
    stats: 1300,
    shares: 20,
    image: "https://picsum.photos/seed/5/600/400",
  },
  {
    id: 10,
    user: "Clementina DuBuque",
    username: "@Moriah.Stanton",
    avatar: "https://i.pravatar.cc/150?u=Moriah.Stanton",
    content: "ab rerum non rerum consequatur ut ea unde",
    comments: 6,
    retweets: 14,
    likes: 68,
    saves: 3,
    stats: 750,
    shares: 10,
  },
  {
    id: 11,
    user: "John Doe",
    username: "@johndoe",
    avatar: "https://i.pravatar.cc/150?u=johndoe",
    content: "Just setting up my twttr",
    comments: 1,
    retweets: 2,
    likes: 3,
    saves: 0,
    stats: 100,
    shares: 1,
  },
  {
    id: 12,
    user: "Jane Smith",
    username: "@janesmith",
    avatar: "https://i.pravatar.cc/150?u=janesmith",
    content: "This is my first tweet!",
    comments: 5,
    retweets: 10,
    likes: 20,
    saves: 1,
    stats: 200,
    shares: 2,
    image: "https://picsum.photos/seed/6/600/400",
  },
  {
    id: 13,
    user: "Alice Johnson",
    username: "@alicej",
    avatar: "https://i.pravatar.cc/150?u=alicej",
    content: "I love Next.js!",
    comments: 10,
    retweets: 20,
    likes: 50,
    saves: 5,
    stats: 500,
    shares: 10,
  },
  {
    id: 14,
    user: "Bob Brown",
    username: "@bobb",
    avatar: "https://i.pravatar.cc/150?u=bobb",
    content: "Firebase is awesome!",
    comments: 15,
    retweets: 30,
    likes: 100,
    saves: 10,
    stats: 1000,
    shares: 20,
  },
  {
    id: 15,
    user: "Charlie Green",
    username: "@charlieg",
    avatar: "https://i.pravatar.cc/150?u=charlieg",
    content: "Just deployed a new app with Firebase Hosting.",
    comments: 20,
    retweets: 40,
    likes: 200,
    saves: 20,
    stats: 2000,
    shares: 40,
    image: "https://picsum.photos/seed/7/600/400",
  },
  {
    id: 16,
    user: "David Black",
    username: "@davidb",
    avatar: "https://i.pravatar.cc/150?u=davidb",
    content: "I\'m learning so much about web development.",
    comments: 25,
    retweets: 50,
    likes: 250,
    saves: 25,
    stats: 2500,
    shares: 50,
  },
  {
    id: 17,
    user: "Eve White",
    username: "@evew",
    avatar: "https://i.pravatar.cc/150?u=evew",
    content: "Just discovered the magic of server components.",
    comments: 30,
    retweets: 60,
    likes: 300,
    saves: 30,
    stats: 3000,
    shares: 60,
  },
  {
    id: 18,
    user: "Frank Blue",
    username: "@frankb",
    avatar: "https://i.pravatar.cc/150?u=frankb",
    content: "I\'m so excited to be a part of this community!",
    comments: 35,
    retweets: 70,
    likes: 350,
    saves: 35,
    stats: 3500,
    shares: 70,
    image: "https://picsum.photos/seed/8/600/400",
  },
  {
    id: 19,
    user: "Grace Pink",
    username: "@gracep",
    avatar: "https://i.pravatar.cc/150?u=gracep",
    content: "Just finished a great book. Highly recommend it!",
    comments: 40,
    retweets: 80,
    likes: 400,
    saves: 40,
    stats: 4000,
    shares: 80,
  },
  {
    id: 20,
    user: "Heidi Yellow",
    username: "@heidiy",
    avatar: "https://i.pravatar.cc/150?u=heidiy",
    content: "I can\'t believe how easy it is to build a full-stack app with Next.js and Firebase.",
    comments: 45,
    retweets: 90,
    likes: 450,
    saves: 45,
    stats: 4500,
    shares: 90,
  }
];

