export const following = [
    {
        id: 1,
        user: "Leanne Graham",
        username: "@Bret",
        avatar: "https://i.pravatar.cc/150?u=Bret",
    },
    {
        id: 2,
        user: "Ervin Howell",
        username: "@Antonette",
        avatar: "https://i.pravatar.cc/150?u=Antonette",
    },
    {
        id: 3,
        user: "Clementine Bauch",
        username: "@Samantha",
        avatar: "https://i.pravatar.cc/150?u=Samantha",
    },
    {
        id: 4,
        user: "Patricia Lebsack",
        username: "@Karianne",
        avatar: "https://i.pravatar.cc/150?u=Karianne",
    },
    {
        id: 5,
        user: "Chelsey Dietrich",
        username: "@Kamren",
        avatar: "https://i.pravatar.cc/150?u=Kamren",
    },
    {
        id: 6,
        user: "Mrs. Dennis Schulist",
        username: "@Leopoldo_Corkery",
        avatar: "https://i.pravatar.cc/150?u=Leopoldo_Corkery",
    },
    {
        id: 7,
        user: "Kurtis Weissnat",
        username: "@Elwyn.Skiles",
        avatar: "https://i.pravatar.cc/150?u=Elwyn.Skiles",
    },
    {
        id: 8,
        user: "Nicholas Runolfsdottir V",
        username: "@Maxime_Nienow",
        avatar: "https://i.pravatar.cc/150?u=Maxime_Nienow",
    },
    {
        id: 9,
        user: "Glenna Reichert",
        username: "@Delphine",
        avatar: "https://i.pravatar.cc/150?u=Delphine",
    },
    {
        id: 10,
        user: "Clementina DuBuque",
        username: "@Moriah.Stanton",
        avatar: "https://i.pravatar.cc/150?u=Moriah.Stanton",
    },
    {
        id: 11,
        user: "John Doe",
        username: "@johndoe",
        avatar: "https://i.pravatar.cc/150?u=johndoe",
    },
    {
        id: 12,
        user: "Jane Smith",
        username: "@janesmith",
        avatar: "https://i.pravatar.cc/150?u=janesmith",
    },
    {
        id: 13,
        user: "Alice Johnson",
        username: "@alicej",
        avatar: "https://i.pravatar.cc/150?u=alicej",
    },
    {
        id: 14,
        user: "Bob Brown",
        username: "@bobb",
        avatar: "https://i.pravatar.cc/150?u=bobb",
    },
    {
        id: 15,
        user: "Charlie Green",
        username: "@charlieg",
        avatar: "https://i.pravatar.cc/150?u=charlieg",
    },
    {
        id: 16,
        user: "David Black",
        username: "@davidb",
        avatar: "https://i.pravatar.cc/150?u=davidb",
    },
    {
        id: 17,
        user: "Eve White",
        username: "@evew",
        avatar: "https://i.pravatar.cc/150?u=evew",
    },
    {
        id: 18,
        user: "Frank Blue",
        username: "@frankb",
        avatar: "https://i.pravatar.cc/150?u=frankb",
    },
    {
        id: 19,
        user: "Grace Pink",
        username: "@gracep",
        avatar: "https://i.pravatar.cc/150?u=gracep",
    },
    {
        id: 20,
        user: "Heidi Yellow",
        username: "@heidiy",
        avatar: "https://i.pravatar.cc/150?u=heidiy",
    },
    {
        id: 21,
        user: "Ivan Violet",
        username: "@ivanv",
        avatar: "https://i.pravatar.cc/150?u=ivanv",
    },
    {
        id: 22,
        user: "Judy Cyan",
        username: "@judyc",
        avatar: "https://i.pravatar.cc/150?u=judyc",
    },
    {
        id: 23,
        user: "Karl Magenta",
        username: "@karlm",
        avatar: "https://i.pravatar.cc/150?u=karlm",
    },
];
